### ISSUE TITLE
Capistrano 3.4.x: Possible bug in the no_release reject code

### ISSUE THREAD

**Issue by klausmeyer** [sepastian/capistrano-unicorn#15]
Hey,

today I've upgraded one of my apps from capistrano 3.3.5 to 3.4.0 and noticed that the unicorn tasks are no more executed. After tracking the issue a bit down I've found the culprit:

https://github.com/sepastian/capistrano-unicorn/blob/c1ebef68d75b773afbee7fd487edfb74917fee56/lib/capistrano/tasks/unicorn.cap#L88

At the moment the `:reject` is passed to the `roles` method instead of the `on`.
Adding parentheses "solved" the issue for me.

```diff
...
  desc 'Start Unicorn master process'
  task :start do
-    on roles unicorn_roles, reject: lambda { |h| h.properties.no_release } do
+    on roles(unicorn_roles), reject: lambda { |h| h.properties.no_release } do
      execute start_unicorn
    end
  end
...
```

But I'm not sure because I don't have enough insight into capistrano's architecture.

Best, Klaus

**Comment by sepastian** [comment]
Thanks @klausmeyer, this has been fixed finally; #17.
